# Generated by Django 2.0.3 on 2020-02-28 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 2, 28, 20, 46, 19, 117725))),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.CharField(default='请完善', max_length=10)),
                ('email', models.CharField(default='请完善', max_length=100)),
                ('phone', models.CharField(default='请完善', max_length=20)),
                ('address', models.TextField(blank=True, default='请完善', null=True)),
                ('intro', models.TextField(blank=True, default='请完善', null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
